version: "3"
services:
  app:
    build: .
    image: leoluyi/markets-shiny
    ports:
      - "8899:3838"
    volumes:
      - ./app:/srv/shiny-server/app
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
