version: "3"
services:
    shiny-app:
        build: .
        ports:
            - "8899:3838"
        volumes:
            - ./app:/srv/shiny-server/app
            - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
