version: "3"
services:
    shiny-app:
        build: .
        ports:
            - "8787:3838"
        volumes:
            - .:/srv/shiny-server/
            - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
